# Generated by Django 5.0.4 on 2024-05-02 01:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tarefa_mes_alter_tarefa_data_alter_tarefa_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tempo_disponivel_semana', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
            },
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(default=datetime.date(2024, 5, 2)),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora',
            field=models.TimeField(default=datetime.time(1, 53, 57, 578126)),
        ),
        migrations.CreateModel(
            name='Elemento_ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_categoria', models.IntegerField(default=0)),
                ('horas_cumpridas', models.IntegerField(default=0)),
                ('dificuldade', models.IntegerField(default=1)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.categoria')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.ciclo')),
            ],
            options={
                'verbose_name': 'Elemento de ciclo',
                'verbose_name_plural': 'Elementos de clico',
                'ordering': ['categoria__nome', 'ciclo__pk'],
            },
        ),
    ]
