# Generated by Django 5.0.4 on 2024-05-02 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_ciclo_alter_tarefa_data_alter_tarefa_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora',
            field=models.TimeField(default=datetime.time(3, 4, 30, 554854)),
        ),
    ]
