# Generated by Django 5.0.4 on 2024-05-16 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_tarefa_options_alter_tarefa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(default=datetime.date(2024, 5, 16)),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 44, 37, 356225)),
        ),
    ]
