# Generated by Django 5.0.4 on 2024-04-28 01:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(default=0.0)),
                ('cofrinho', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Saldo',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('hora', models.TimeField(default=datetime.time(1, 17, 35, 338450))),
                ('data', models.DateField()),
                ('visibilidade', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
                'ordering': ['nome', 'data', 'categoria', 'pk'],
            },
        ),
    ]
