# Generated by Django 5.0.4 on 2024-04-28 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.date(2024, 4, 28)),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='hora',
            field=models.TimeField(default=datetime.time(1, 19, 12, 135017)),
        ),
    ]
