# Generated by Django 5.0.4 on 2024-05-01 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0011_alter_movimentacao_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.date(2024, 5, 1)),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 38, 14, 757622)),
        ),
    ]
